CREATE TABLE `course_history` (
    `userid` VARCHAR(50),
    `history` VARCHAR(255),
    PRIMARY KEY (`userid`)
);

CREATE TABLE `login` (
    `userid` VARCHAR(50),
    `password` VARCHAR(50),
    `visits` INT(11),
    PRIMARY KEY (`userid`)
);
    
CREATE TABLE `cc_area_description` (
    `course_area` VARCHAR(255),
    `area_description` VARCHAR(255),
    PRIMARY KEY (`course_area`)
);

insert into cc_area_description values
('A', 'English Communication: 9 semester units'),
('A1', 'Oral Communication'),
('A2', 'Written Communication'),
('A3', 'Critical Thinking'),
('B', 'Scientific Inquiry and Quantitative Reasoning: 12 semester units, with 3 units taken at the upper-division level'),
('B1', 'Physical Science'),
('B2', 'Life Science'),
('B3', 'Laboratory Activity(taken in conjunction with B1 or B2)'),
('B4', 'Mathematics/Quantitative Reasoning'),
('C', 'Arts and Humanities: 12 semester units, with 3 units taken at the upper-division level'),
('C1', 'Arts: Arts, Cinema, Dance, Music, Theater'),
('C2', 'Humanities: Literature, Philosophy, Languanges Other than English'),
('D', 'Social Sciences: 12 semester units, with 3 units taken at the upper-division level'),
('D0', 'Sociology and Criminology'),
('D1', 'Anthropology and Archeology'),
('D2', 'Economics'),
('D3', 'Ethnic Students'),
('D4', 'Gender Studies'),
('D5', 'Geography'),
('D6', 'History'),
('D7', 'Interdisciplinary Social or Behavioral Science'),
('D8', 'Political Science, Government, and Legal Institutions'),
('D9', 'Psychology'),
('E', 'Lifelong Learning and Self-Development: 3 semester units');

CREATE TABLE `cc_courses` (
  `course_id` int(11) NOT NULL AUTO_INCREMENT,
  `college` varchar(5) NOT NULL,
  `course_code` varchar(8) NOT NULL,
  `course_title` varchar(255) NOT NULL,
  `course_units` int(11) NOT NULL,
  `course_area` varchar(3) NOT NULL,
  PRIMARY KEY (`course_id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=latin1;

INSERT INTO cc_courses VALUES (NULL,"RCC","ADJ 1","Introduction to the Administration of Justice",3,"D0");
INSERT INTO cc_courses VALUES (NULL,"RCC","ADJ 3","Concepts of Criminal Law",3,"D8");
INSERT INTO cc_courses VALUES (NULL,"RCC","ADJ 9","Law in American Society",3,"D0");
INSERT INTO cc_courses VALUES (NULL,"RCC","AML 1","American Sign Language I",4,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","AML 1A","American Sign Language 1A",2,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","AML 1B","American Sign Language 1B",2,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","AML 2","American Sign Language 2",4,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","AML 3","American Sign Language 3",4,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","AML 4","American Sign Language 4",4,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","AML 5","Sign Language for Interpreters",4,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","AMY 2A","Anatomy and Physiology I",4,"B2");
INSERT INTO cc_courses VALUES (NULL,"RCC","AMY 2A","Anatomy and Physiology I",4,"B3");
INSERT INTO cc_courses VALUES (NULL,"RCC","AMY 2B","Anatomy and Physiology II",4,"B2");
INSERT INTO cc_courses VALUES (NULL,"RCC","AMY 2B","Anatomy and Physiology II",4,"B3");
INSERT INTO cc_courses VALUES (NULL,"RCC","AMY 10","Survey of Human Anatomy & Physiology",3,"B2");
INSERT INTO cc_courses VALUES (NULL,"RCC","ANT 1","Physical Anthropology",3,"B2");
INSERT INTO cc_courses VALUES (NULL,"RCC","ANT 1H","Honors Physical Anthropology",3,"B2");
INSERT INTO cc_courses VALUES (NULL,"RCC","ANT 2","Cultural Anthropology",3,"D1");
INSERT INTO cc_courses VALUES (NULL,"RCC","ANT 3","Prehistoric Cultures",3,"D1");
INSERT INTO cc_courses VALUES (NULL,"RCC","ANT 4","Native American Cultures",3,"D1");
INSERT INTO cc_courses VALUES (NULL,"RCC","ANT 4","Native American Cultures",3,"D3");
INSERT INTO cc_courses VALUES (NULL,"RCC","ANT 5","Cultures of Ancient Mexico",3,"D1");
INSERT INTO cc_courses VALUES (NULL,"RCC","ANT 6","Introduction to Archaeology",3,"D1");
INSERT INTO cc_courses VALUES (NULL,"RCC","ANT 7","Anthropology of Religion",3,"D1");
INSERT INTO cc_courses VALUES (NULL,"RCC","ANT 8","Language and Culture",3,"D1");
INSERT INTO cc_courses VALUES (NULL,"RCC","ANT 10","Forensic Anthropology",3,"D1");
INSERT INTO cc_courses VALUES (NULL,"RCC","ANT 20","Introduction to the Primates",3,"D1");
INSERT INTO cc_courses VALUES (NULL,"RCC","ANT 21","Peoples of Sub-Saharan Africa",3,"D1");
INSERT INTO cc_courses VALUES (NULL,"RCC","ARA 1","Arabic 1",5,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","ARA 1A","Arabic 1A",2.5,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","ARA 1B","Arabic 1B",2.5,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","ARA 2","Arabic 2",5,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","ARA 3","Arabic 3",5,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","ARA 8","Intermediate Conversation",3,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","ARA 11","Culture and Civilization",3,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","ARCH 3","History of Architecture",3,"C1");
INSERT INTO cc_courses VALUES (NULL,"RCC","ARE 35","History of Architecture - Beginnings of Architecture through Gothic Architecture",3,"C1");
INSERT INTO cc_courses VALUES (NULL,"RCC","ARE 36","History of Architecture - Renaissance to Modern",3,"C1");
INSERT INTO cc_courses VALUES (NULL,"RCC","ART 1","History of Western Art: Prehistoric, Ancient and Medieval",3,"C1");
INSERT INTO cc_courses VALUES (NULL,"RCC","ART 2","History of Western Art: Renaissance through Contemporary",3,"C1");
INSERT INTO cc_courses VALUES (NULL,"RCC","ART 2H","Honors Art History of Western Art: Renaissance through Contemporary",3,"C1");
INSERT INTO cc_courses VALUES (NULL,"RCC","ART 4","Introduction to Visual Culture",3,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","ART 5","History of Non-Western Art",3,"C1");
INSERT INTO cc_courses VALUES (NULL,"RCC","ART 5","History of Non-Western Art",3,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","ART 6","Art Appreciation",3,"C1");
INSERT INTO cc_courses VALUES (NULL,"RCC","ART 6H","Honors Art Appreciation",3,"C1");
INSERT INTO cc_courses VALUES (NULL,"RCC","ART 7","Women Artists in History",3,"C1");
INSERT INTO cc_courses VALUES (NULL,"RCC","ART 8","Mexican Art History",3,"C1");
INSERT INTO cc_courses VALUES (NULL,"RCC","ART 9","African Art History",3,"C1");
INSERT INTO cc_courses VALUES (NULL,"RCC","ART 10","Modern and Contemporary Art History",3,"C1");
INSERT INTO cc_courses VALUES (NULL,"RCC","ART 12","Asian Art History",3,"C1");
INSERT INTO cc_courses VALUES (NULL,"RCC","ART 13","Pre-Columbian Art History",3,"C1");
INSERT INTO cc_courses VALUES (NULL,"RCC","ART 14","Latin American Art: Colonial to the Present",3,"C1");
INSERT INTO cc_courses VALUES (NULL,"RCC","AST 1A","Introduction to the Solar System",3,"B1");
INSERT INTO cc_courses VALUES (NULL,"RCC","AST 1B","Introduction to the Stars and Galaxies",3,"B1");
INSERT INTO cc_courses VALUES (NULL,"RCC","BIO 1","General Biology",4,"B2");
INSERT INTO cc_courses VALUES (NULL,"RCC","BIO 1","General Biology",4,"B3");
INSERT INTO cc_courses VALUES (NULL,"RCC","BIO 1H","Honors General Biology",4,"B2");
INSERT INTO cc_courses VALUES (NULL,"RCC","BIO 1H","Honors General Biology",4,"B3");
INSERT INTO cc_courses VALUES (NULL,"RCC","BIO 2A","Invertebrate Zoology",5,"B2");
INSERT INTO cc_courses VALUES (NULL,"RCC","BIO 2A","Invertebrate Zoology",5,"B3");
INSERT INTO cc_courses VALUES (NULL,"RCC","BIO 2B","Vertebrate Zoology",5,"B2");
INSERT INTO cc_courses VALUES (NULL,"RCC","BIO 2B","Vertebrate Zoology",5,"B3");
INSERT INTO cc_courses VALUES (NULL,"RCC","BIO 3","Field Botany",4,"B2");
INSERT INTO cc_courses VALUES (NULL,"RCC","BIO 3","Field Botany",4,"B3");
INSERT INTO cc_courses VALUES (NULL,"RCC","BIO 5","General Botany",4,"B2");
INSERT INTO cc_courses VALUES (NULL,"RCC","BIO 5","General Botany",4,"B3");
INSERT INTO cc_courses VALUES (NULL,"RCC","BIO 6","Introduction to Zoology",4,"B2");
INSERT INTO cc_courses VALUES (NULL,"RCC","BIO 6","Introduction to Zoology",4,"B3");
INSERT INTO cc_courses VALUES (NULL,"RCC","BIO 7","Marine Biology",4,"B2");
INSERT INTO cc_courses VALUES (NULL,"RCC","BIO 7","Marine Biology",4,"B3");
INSERT INTO cc_courses VALUES (NULL,"RCC","BIO 8","Principles of Ecology",4,"B2");
INSERT INTO cc_courses VALUES (NULL,"RCC","BIO 8","Principles of Ecology",4,"B3");
INSERT INTO cc_courses VALUES (NULL,"RCC","BIO 8L","Ecology Lab",1,"B2");
INSERT INTO cc_courses VALUES (NULL,"RCC","BIO 8L","Ecology Lab",1,"B3");
INSERT INTO cc_courses VALUES (NULL,"RCC","BIO 9","Introduction to the Natural History of Southern California",3,"B2");
INSERT INTO cc_courses VALUES (NULL,"RCC","BIO 10","Life Science Principles",3,"B2");
INSERT INTO cc_courses VALUES (NULL,"RCC","BIO 11","Introduction to Molecular and Cellular Biology",5,"B2");
INSERT INTO cc_courses VALUES (NULL,"RCC","BIO 12","Introduction to Organismal and Population Biology",5,"B2");
INSERT INTO cc_courses VALUES (NULL,"RCC","BIO 14","Soil Science and Management",3,"B2");
INSERT INTO cc_courses VALUES (NULL,"RCC","BIO 15","Soil Science and Management Laboratory",2,"B3");
INSERT INTO cc_courses VALUES (NULL,"RCC","BIO 17","Human Biology",4,"B2");
INSERT INTO cc_courses VALUES (NULL,"RCC","BIO 17","Human Biology",4,"B3");
INSERT INTO cc_courses VALUES (NULL,"RCC","BIO 20","Plants and Human Affairs",3,"B2");
INSERT INTO cc_courses VALUES (NULL,"RCC","BIO 30","Human Reproduction and Sexual Behavior",3,"E");
INSERT INTO cc_courses VALUES (NULL,"RCC","BIO 34","Human Genetics",3,"B2");
INSERT INTO cc_courses VALUES (NULL,"RCC","BIO 36","Environmental Science",3,"B2");
INSERT INTO cc_courses VALUES (NULL,"RCC","CHE 1A","General Chemistry, I",5,"B1");
INSERT INTO cc_courses VALUES (NULL,"RCC","CHE 1A","General Chemistry, I",5,"B3");
INSERT INTO cc_courses VALUES (NULL,"RCC","CHE 1A","Honors General Chemistry, I",5,"B1");
INSERT INTO cc_courses VALUES (NULL,"RCC","CHE 1A","Honors General Chemistry, I",5,"B3");
INSERT INTO cc_courses VALUES (NULL,"RCC","CHE 1B","General Chemistry, II",5,"B1");
INSERT INTO cc_courses VALUES (NULL,"RCC","CHE 1B","General Chemistry, II",5,"B3");
INSERT INTO cc_courses VALUES (NULL,"RCC","CHE 1B","Honors General Chemistry, II",5,"B1");
INSERT INTO cc_courses VALUES (NULL,"RCC","CHE 1B","Honors General Chemistry, II",5,"B3");
INSERT INTO cc_courses VALUES (NULL,"RCC","CHE 2A","Introductory Chemistry, I",4,"B1");
INSERT INTO cc_courses VALUES (NULL,"RCC","CHE 2A","Introductory Chemistry, I",4,"B3");
INSERT INTO cc_courses VALUES (NULL,"RCC","CHE 2B","Introductory Chemistry, II",4,"B1");
INSERT INTO cc_courses VALUES (NULL,"RCC","CHE 2B","Introductory Chemistry, II",4,"B3");
INSERT INTO cc_courses VALUES (NULL,"RCC","CHE 3","Fundamentals of Chemistry",4,"B1");
INSERT INTO cc_courses VALUES (NULL,"RCC","CHE 3","Fundamentals of Chemistry",4,"B3");
INSERT INTO cc_courses VALUES (NULL,"RCC","CHE 5","Quantitative Analysis",3,"B1");
INSERT INTO cc_courses VALUES (NULL,"RCC","CHE 8","Elementary Organic Chemistry",4,"B1");
INSERT INTO cc_courses VALUES (NULL,"RCC","CHE 8","Elementary Organic Chemistry",4,"B3");
INSERT INTO cc_courses VALUES (NULL,"RCC","CHE 9","Introduction to Scientific Computer Programming",3,"B4");
INSERT INTO cc_courses VALUES (NULL,"RCC","CHE 10","Chemistry for Everyone",3,"B1");
INSERT INTO cc_courses VALUES (NULL,"RCC","CHE 12","Organic Chemistry, I",5,"B1");
INSERT INTO cc_courses VALUES (NULL,"RCC","CHE 12","Organic Chemistry, I",5,"B3");
INSERT INTO cc_courses VALUES (NULL,"RCC","CHE 12","Organic Chemistry, II",5,"B1");
INSERT INTO cc_courses VALUES (NULL,"RCC","CHE 12","Organic Chemistry, II",5,"B3");
INSERT INTO cc_courses VALUES (NULL,"RCC","CHE 17","Introduction to the Development of Modern Science",3,"D6");
INSERT INTO cc_courses VALUES (NULL,"RCC","CHI 1","Mandarin Chinese 1",5,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","CHI 1A","Mandarin Chinese 1A",2.5,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","CHI 1B","Mandarin Chinese 1B",2.5,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","CHI 2","Chinese 2",5,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","CHI 11","Culture and Civilization",3,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","COM 1","Public Speaking",3,"A1");
INSERT INTO cc_courses VALUES (NULL,"RCC","COM 1H","Honors Public Speaking",3,"A1");
INSERT INTO cc_courses VALUES (NULL,"RCC","COM 2","Persuasion in Rhetorical Perspective",3,"A3");
INSERT INTO cc_courses VALUES (NULL,"RCC","COM 3","Argumentation and Debate",3,"A3");
INSERT INTO cc_courses VALUES (NULL,"RCC","COM 5","Parliamentary Procedure",1,"A3");
INSERT INTO cc_courses VALUES (NULL,"RCC","COM 6","Dynamics of Small Group Communication",3,"A1");
INSERT INTO cc_courses VALUES (NULL,"RCC","COM 9","Interpersonal Communication",3,"A1");
INSERT INTO cc_courses VALUES (NULL,"RCC","COM 9","Interpersonal Communication",3,"D7");
INSERT INTO cc_courses VALUES (NULL,"RCC","COM 9H","Honors Interpersonal Communication",3,"A1");
INSERT INTO cc_courses VALUES (NULL,"RCC","COM 11","Storytelling",3,"C1");
INSERT INTO cc_courses VALUES (NULL,"RCC","COM 12","Intercultural Communication",3,"D7");
INSERT INTO cc_courses VALUES (NULL,"RCC","COM 13","Gender and Communication",3,"D4");
INSERT INTO cc_courses VALUES (NULL,"RCC","CSC 6","Discrete Mathematics for Computer Science",3,"B4");
INSERT INTO cc_courses VALUES (NULL,"RCC","DAN 6","Dance Appreciation",3,"C1");
INSERT INTO cc_courses VALUES (NULL,"RCC","DAN 6H","Honors Dance Appreciation",3,"C1");
INSERT INTO cc_courses VALUES (NULL,"RCC","DAN D1","Dance Repertoire, Modern",1,"E");
INSERT INTO cc_courses VALUES (NULL,"RCC","DAN D1","Dance Repertoire, Jazz",1,"E");
INSERT INTO cc_courses VALUES (NULL,"RCC","DAN D1","Dance Repertoire, Ballet",1,"E");
INSERT INTO cc_courses VALUES (NULL,"RCC","DAN D1","Dance Repertoire, Tap",1,"E");
INSERT INTO cc_courses VALUES (NULL,"RCC","DAN D1","Dance Repertoire, Ethnic",1,"E");
INSERT INTO cc_courses VALUES (NULL,"RCC","DAN D2","Introduction to Social Dance",1,"E");
INSERT INTO cc_courses VALUES (NULL,"RCC","DAN D2","Ballet, Beginning",1,"E");
INSERT INTO cc_courses VALUES (NULL,"RCC","DAN D2","Ballet, Intermediate",1,"E");
INSERT INTO cc_courses VALUES (NULL,"RCC","DAN D2","Ballet, Advanced",1,"E");
INSERT INTO cc_courses VALUES (NULL,"RCC","DAN D2","Pointe Technique, Beginning",1,"E");
INSERT INTO cc_courses VALUES (NULL,"RCC","DAN D2","Floor Barre",1,"E");
INSERT INTO cc_courses VALUES (NULL,"RCC","DAN D3","Social Dance Styles",1,"E");
INSERT INTO cc_courses VALUES (NULL,"RCC","DAN D3","Hip-Hop Dance, Beginning",1,"E");
INSERT INTO cc_courses VALUES (NULL,"RCC","DAN D3","Hip-Hop Dance, Intermediate",1,"E");
INSERT INTO cc_courses VALUES (NULL,"RCC","DAN D3","Jazz, Beginning",1,"E");
INSERT INTO cc_courses VALUES (NULL,"RCC","DAN D3","Jazz, Intermediate",1,"E");
INSERT INTO cc_courses VALUES (NULL,"RCC","DAN D3","Jazz, Advanced",1,"E");
INSERT INTO cc_courses VALUES (NULL,"RCC","DAN D3","Modern Dance, Beginning",1,"E");
INSERT INTO cc_courses VALUES (NULL,"RCC","DAN D3","Modern Dance, Intermediate",1,"E");
INSERT INTO cc_courses VALUES (NULL,"RCC","DAN D3","Modern Dance, Advanced",1,"E");
INSERT INTO cc_courses VALUES (NULL,"RCC","DAN D4","Tap, Beginning",1,"E");
INSERT INTO cc_courses VALUES (NULL,"RCC","DAN D4","Tap, Intermediate",1,"E");
INSERT INTO cc_courses VALUES (NULL,"RCC","DAN D4","Tap, Advanced",1,"E");
INSERT INTO cc_courses VALUES (NULL,"RCC","DAN D4","Pilates Mat Work",1,"E");
INSERT INTO cc_courses VALUES (NULL,"RCC","DAN D4","Pilates Beginning",1,"E");
INSERT INTO cc_courses VALUES (NULL,"RCC","DAN D4","Universal Reformer Technique",1,"E");
INSERT INTO cc_courses VALUES (NULL,"RCC","DAN D4","Pilates, Intermediate",1,"E");
INSERT INTO cc_courses VALUES (NULL,"RCC","DAN D5","Pilates for Dancers",1,"E");
INSERT INTO cc_courses VALUES (NULL,"RCC","DAN D5","Pilates, Advanced",1,"E");
INSERT INTO cc_courses VALUES (NULL,"RCC","DAN D6","Dance Techniques for Musical Theater",0.5,"E");
INSERT INTO cc_courses VALUES (NULL,"RCC","EAR 20","Child Growth and Development",3,"D7");
INSERT INTO cc_courses VALUES (NULL,"RCC","EAR 20","Child Growth and Development",3,"E");
INSERT INTO cc_courses VALUES (NULL,"RCC","EAR 42","Child, Family and Community",3,"D7");
INSERT INTO cc_courses VALUES (NULL,"RCC","EAR 42","Child, Family and Community",3,"E");
INSERT INTO cc_courses VALUES (NULL,"RCC","ECS 20","Child Development",3,"E");
INSERT INTO cc_courses VALUES (NULL,"RCC","ECO 4","Introduction to Economics",3,"D2");
INSERT INTO cc_courses VALUES (NULL,"RCC","ECO 4","Introduction to Economics",3,"D3");
INSERT INTO cc_courses VALUES (NULL,"RCC","ECO 5","Economics of the Environment",3,"D2");
INSERT INTO cc_courses VALUES (NULL,"RCC","ECO 6","Introduction to Political Economy",3,"D2");
INSERT INTO cc_courses VALUES (NULL,"RCC","ECO 7","Principles of Macroeconomics",3,"D2");
INSERT INTO cc_courses VALUES (NULL,"RCC","ECO 7","Principles of Macroeconomics",3,"D3");
INSERT INTO cc_courses VALUES (NULL,"RCC","ECO 7H","Honors Principles of Macroeconomics",3,"D2");
INSERT INTO cc_courses VALUES (NULL,"RCC","ECO 8","Principles of Microeconomics",3,"D2");
INSERT INTO cc_courses VALUES (NULL,"RCC","ECO 8","Principles of Microeconomics",3,"D3");
INSERT INTO cc_courses VALUES (NULL,"RCC","ECO 8H","Honors Principles of Microeconomics",3,"D2");
INSERT INTO cc_courses VALUES (NULL,"RCC","ECO 9","Economics of Poverty and Discrimination",3,"D2");
INSERT INTO cc_courses VALUES (NULL,"RCC","ECO 10","Economics and Personal Decision-Making",3,"D2");
INSERT INTO cc_courses VALUES (NULL,"RCC","ENE 9","Introduction to Scientific Computer Programming",3,"B4");
INSERT INTO cc_courses VALUES (NULL,"RCC","ENE 36","History of Architecture",3,"C1");
INSERT INTO cc_courses VALUES (NULL,"RCC","ENG 1A","English Composition",4,"A2");
INSERT INTO cc_courses VALUES (NULL,"RCC","ENG 1A","Honors English Composition",4,"A2");
INSERT INTO cc_courses VALUES (NULL,"RCC","ENG 1B","Critical Thinking and Writing",4,"A3");
INSERT INTO cc_courses VALUES (NULL,"RCC","ENG 1B","Honors Critical Thinking and Writing",4,"A3");
INSERT INTO cc_courses VALUES (NULL,"RCC","ENG 6","British Literature I: Anglo-Saxon through Eighteenth Century",3,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","ENG 7","British Literature II: Romanticism through Modernism/Postmodernism",3,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","ENG 8","Introduction to Mythology",3,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","ENG 9","Introduction to Shakespeare",3,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","ENG 11","Creative Writing",3,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","ENG 11","Creative Writing I",3,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","ENG 11","Creative Writing II",3,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","ENG 12","Special Studies in Creative Writing",3,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","ENG 14","American Literature I: Pre-Contact through Civil War",3,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","ENG 15","American Literature II: 1860 to the Present",3,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","ENG 16","Introduction to Linguistics",3,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","ENG 18","Survey of Native American LIterature",3,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","ENG 20","Survey of African American Literature",3,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","ENG 20","Advanced Grammar, Usage and Style",3,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","ENG 21","African-American Literature I: Early Oral Traditions through Harlem Renaissance",3,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","ENG 22","African-American Literature II: From the Harlem Renaissanceto the Present",3,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","ENG 23","The Bible as Literature",3,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","ENG 25","Latino Literature of the United States",3,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","ENG 26","The Literature of Mysticism, Meditation and Madness",3,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","ENG 30","Children's Literature",3,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","ENG 34","Literature By Women",3,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","ENG 35","Images of Women in Literature",3,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","ENG 36","Introduction to Film Studies",3,"C1");
INSERT INTO cc_courses VALUES (NULL,"RCC","ENG 37","Film Appreciation",1,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","ENG 40","World Literature I: From Ancient Literatures to the Seventeenth Century",3,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","ENG 41","World Literature II: Seventeenth Century Through the Present",3,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","ENG 42","Far and Near: The Literature of the East",3,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","ENG 44","Poetry from the Twentieth Century to the Present",3,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","ENG 45","Modern Drama",3,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","ENG 48","Short Story and Novel from the Twentieth Century to the Present",3,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","FST 1","Introduction to Film Studies",3,"C1");
INSERT INTO cc_courses VALUES (NULL,"RCC","FST 2","Introduction to Television Studies",3,"C1");
INSERT INTO cc_courses VALUES (NULL,"RCC","FST 3","Introduction to International Cinema",3,"C1");
INSERT INTO cc_courses VALUES (NULL,"RCC","FST 4","Introduction to Film Genres",3,"C1");
INSERT INTO cc_courses VALUES (NULL,"RCC","FST 5","Fiction and Film: Adaptation",3,"C1");
INSERT INTO cc_courses VALUES (NULL,"RCC","FST 5","Fiction and Film: Adaptation",3,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","FST 6","Screenplay Analysis: The Craft of the Screenplay",3,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","FST 7","History of World Film I: From the Beginning through the 1950's",3,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","FST 8","History of World Film II: The 1950's to the Present",3,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","FTV 12","History of American Film",3,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","FTV 41","Introduction to Telecommunications",3,"D7");
INSERT INTO cc_courses VALUES (NULL,"RCC","FTV 65","The Director's Art in Filmmaking",3,"C1");
INSERT INTO cc_courses VALUES (NULL,"RCC","FRE 1","French 1",5,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","FRE 2","French 2",5,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","FRE 3","French 3",5,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","FRE 4","French 4",5,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","FRE 8","Intermediate Conversation",3,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","FRE 11","Culture and Civilization",3,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","GEG 1","Physical Geography",3,"B1");
INSERT INTO cc_courses VALUES (NULL,"RCC","GEG 1H","Honors Physical Geography",3,"B1");
INSERT INTO cc_courses VALUES (NULL,"RCC","GEG 1L","Physical Geography Laboratory",1,"B1");
INSERT INTO cc_courses VALUES (NULL,"RCC","GEG 2","Human Geography",3,"D1");
INSERT INTO cc_courses VALUES (NULL,"RCC","GEG 2","Human Geography",3,"D5");
INSERT INTO cc_courses VALUES (NULL,"RCC","GEG 3","World Regional Geography",3,"D1");
INSERT INTO cc_courses VALUES (NULL,"RCC","GEG 3","World Regional Geography",3,"D5");
INSERT INTO cc_courses VALUES (NULL,"RCC","GEG 4","Geography of California",3,"D1");
INSERT INTO cc_courses VALUES (NULL,"RCC","GEG 4","Geography of California",3,"D5");
INSERT INTO cc_courses VALUES (NULL,"RCC","GEG 5","Weather and Climate",3,"B1");
INSERT INTO cc_courses VALUES (NULL,"RCC","GEG 6","Geography of the United States and Canada",3,"D1");
INSERT INTO cc_courses VALUES (NULL,"RCC","GEO 1","Physical Geology",3,"B1");
INSERT INTO cc_courses VALUES (NULL,"RCC","GEO 1A","Physical Geology",4,"B1");
INSERT INTO cc_courses VALUES (NULL,"RCC","GEO 1A","Physical Geology",4,"B3");
INSERT INTO cc_courses VALUES (NULL,"RCC","GEO 1B","Historical Geology",4,"B1");
INSERT INTO cc_courses VALUES (NULL,"RCC","GEO 1B","Historical Geology",4,"B3");
INSERT INTO cc_courses VALUES (NULL,"RCC","GEO 1L","Physical Geology Laboratory",1,"B3");
INSERT INTO cc_courses VALUES (NULL,"RCC","GEO 2","Geology of the National Parks & Monuments",3,"B1");
INSERT INTO cc_courses VALUES (NULL,"RCC","GEO 3","Geology of California",3,"B1");
INSERT INTO cc_courses VALUES (NULL,"RCC","GER 1","German 1",5,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","GER 2","German 2",5,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","GER 3","German 3",5,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","GER 4","German 4",5,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","GER 11","Culture and Civilization",3,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","GRK 1","Ancient Greek I",5,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","GRK 2","Ancient Greek 2",5,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","GUI 47","Career Exploration and Life Planning",3,"E");
INSERT INTO cc_courses VALUES (NULL,"RCC","GUI 48","College Success Strategies",2,"E");
INSERT INTO cc_courses VALUES (NULL,"RCC","HEALTH","Health Science",3,"E");
INSERT INTO cc_courses VALUES (NULL,"RCC","HEALTH","Nutrition",3,"E");
INSERT INTO cc_courses VALUES (NULL,"RCC","HEALTH","Health Needs in A Modern Society",3,"E");
INSERT INTO cc_courses VALUES (NULL,"RCC","HES 1","Health Science",3,"E");
INSERT INTO cc_courses VALUES (NULL,"RCC","HES 4","Nutrition",3,"E");
INSERT INTO cc_courses VALUES (NULL,"RCC","HIS 1","History of World Civilizations I",3,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","HIS 2","History of World Civilizations II",3,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","HIS 4","History of Western Civilization Civilization",3,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","HIS 5","History of Western Civilization Civilization",3,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","HIS 6","Political and Social History of the United States",3,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","HIS 6H","Honors Political and Social History of the United States",3,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","HIS 7","Political and Social History of the United States",3,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","HIS 7H","Honors Political and Social History of the United States",3,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","HIS 8","History of the Americas",3,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","HIS 8","History of the Americas",3,"D5");
INSERT INTO cc_courses VALUES (NULL,"RCC","HIS 8","History of the Americas",3,"D6");
INSERT INTO cc_courses VALUES (NULL,"RCC","HIS 9","History of the Americas",3,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","HIS 9","History of the Americas",3,"D5");
INSERT INTO cc_courses VALUES (NULL,"RCC","HIS 9","History of the Americas",3,"D6");
INSERT INTO cc_courses VALUES (NULL,"RCC","HIS 11","Military History of the U.S. to 1900",3,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","HIS 12","Military History of the U.S. Since 1900",3,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","HIS 14","African American History I",3,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","HIS 14","African American History I",3,"D3");
INSERT INTO cc_courses VALUES (NULL,"RCC","HIS 14","African American History I",3,"D5");
INSERT INTO cc_courses VALUES (NULL,"RCC","HIS 14","African American History I",3,"D6");
INSERT INTO cc_courses VALUES (NULL,"RCC","HIS 15","African American History II",3,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","HIS 15","African American History II",3,"D3");
INSERT INTO cc_courses VALUES (NULL,"RCC","HIS 15","African American History II",3,"D5");
INSERT INTO cc_courses VALUES (NULL,"RCC","HIS 15","African American History II",3,"D6");
INSERT INTO cc_courses VALUES (NULL,"RCC","HIS 19","Modern Russia History",3,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","HIS 19","Modern Russia History",3,"D5");
INSERT INTO cc_courses VALUES (NULL,"RCC","HIS 19","Modern Russia History",3,"D6");
INSERT INTO cc_courses VALUES (NULL,"RCC","HIS 21","History of Ancient Greece",3,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","HIS 21","History of Ancient Greece",3,"D6");
INSERT INTO cc_courses VALUES (NULL,"RCC","HIS 22","History of Ancient Rome",3,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","HIS 22","History of Ancient Rome",3,"D6");
INSERT INTO cc_courses VALUES (NULL,"RCC","HIS 23","History of the Middle East",3,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","HIS 23","History of the Middle East",3,"D5");
INSERT INTO cc_courses VALUES (NULL,"RCC","HIS 23","History of the Middle East",3,"D6");
INSERT INTO cc_courses VALUES (NULL,"RCC","HIS 25","History of Mexico",3,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","HIS 25","History of Mexico",3,"D5");
INSERT INTO cc_courses VALUES (NULL,"RCC","HIS 25","History of Mexico",3,"D6");
INSERT INTO cc_courses VALUES (NULL,"RCC","HIS 26","History of California",3,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","HIS 26","History of California",3,"D5");
INSERT INTO cc_courses VALUES (NULL,"RCC","HIS 26","History of California",3,"D6");
INSERT INTO cc_courses VALUES (NULL,"RCC","HIS 28","Native American History I: Early Contact Period",3,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","HIS 29","Native American History II: Contemporary Society",3,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","HIS 30","Introduction to Chicano Studies Studies Studies",3,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","HIS 31","Introduction to Chicano/a Studies Studies Studies",3,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","HIS 32","Colonial Latin America",3,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","HIS 32","Colonial Latin America",3,"D6");
INSERT INTO cc_courses VALUES (NULL,"RCC","HIS 34","History of Women in America",3,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","HIS 34","History of Women in America",3,"D4");
INSERT INTO cc_courses VALUES (NULL,"RCC","HIS 34","History of Women in America",3,"D5");
INSERT INTO cc_courses VALUES (NULL,"RCC","HIS 34","History of Women in America",3,"D6");
INSERT INTO cc_courses VALUES (NULL,"RCC","HIS 35","History of England",3,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","HIS 35","History of England",3,"D5");
INSERT INTO cc_courses VALUES (NULL,"RCC","HIS 35","History of England",3,"D6");
INSERT INTO cc_courses VALUES (NULL,"RCC","HIS 40","Oral History",3,"D5");
INSERT INTO cc_courses VALUES (NULL,"RCC","HIS 40","Oral History",3,"D6");
INSERT INTO cc_courses VALUES (NULL,"RCC","HOM 4","Nutrition",3,"E");
INSERT INTO cc_courses VALUES (NULL,"RCC","HOM 7","Child Development",3,"E");
INSERT INTO cc_courses VALUES (NULL,"RCC","HUM 1A","Honors Colloquium I",3,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","HUM 1B","Honors Colloquium II",3,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","HUM 3","Creativity and the Imagination",3,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","HUM 4","Arts and Ideas: Ancient World through the Late Medieval Period",3,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","HUM 4H","Honors Arts and Ideas: Ancient World through the Late Medieval Period",3,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","HUM 5","Arts and Ideas: The Renaissance through the Modern Era",3,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","HUM 5H","Honors Arts and Ideas: The Renaissance through the Modern Era",3,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","HUM 6","Arts and Ideas: Classic through Renaissance",3,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","HUM 7","Arts and Ideas: Renaissance to Modern",3,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","HUM 8","Introduction to Mythology",3,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","HUM 9","American Voices",3,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","HUM 10","World Religions",3,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","HUM 10","Honors World Religions",3,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","HUM 11","Religion in America",3,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","HUM 16","Arts and Ideas: American Culture",3,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","HUM 18","Death: An Interdisciplinary Perspective",3,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","HUM 23","The Bible as Literature",3,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","HUM 35","Philosophy of Religion",3,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","HUM 36","Introduction to Film Studies",3,"C1");
INSERT INTO cc_courses VALUES (NULL,"RCC","HUM 45","A Survey of Artistic Expression in American Culture",3,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","ITA 1","Italian 1",5,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","ITA 2","Italian 2",5,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","ITA 3","Italian 3",5,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","ITA 11","Culture and Civilization",3,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","43466","Japanese 1",5,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","43467","Japanese 2",5,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","43468","Japanese 3",5,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","43469","Japanese 4",5,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","43476","Culture and Civilization",3,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","JPN 1","Japanese 1",5,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","JPN 2","Japanese 2",5,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","JPN 3","Japanese 3",5,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","JPN 4","Japanese 4",5,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","JPN 11","Culture and Civilization",3,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","JOU 7","Mass Communications",3,"D7");
INSERT INTO cc_courses VALUES (NULL,"RCC","JUS 1","Introduction to Administration of Justice",3,"D0");
INSERT INTO cc_courses VALUES (NULL,"RCC","JUS 3","Concepts of Criminal Law",3,"D8");
INSERT INTO cc_courses VALUES (NULL,"RCC","JUS 9","Law in American Society",3,"D0");
INSERT INTO cc_courses VALUES (NULL,"RCC","KIN A3","Adaptive Physical Fitness",1,"E");
INSERT INTO cc_courses VALUES (NULL,"RCC","KIN 4","Nutrition",3,"E");
INSERT INTO cc_courses VALUES (NULL,"RCC","KIN A4","Adaptive Water Exercise",1,"E");
INSERT INTO cc_courses VALUES (NULL,"RCC","KIN A7","Badminton",1,"E");
INSERT INTO cc_courses VALUES (NULL,"RCC","KIN A9","Racquetball",1,"E");
INSERT INTO cc_courses VALUES (NULL,"RCC","KIN 10","Introduction to Kinesiology",3,"E");
INSERT INTO cc_courses VALUES (NULL,"RCC","KIN A1","Tennis, Beginning",1,"E");
INSERT INTO cc_courses VALUES (NULL,"RCC","KIN 12","Sport Psychology",3,"E");
INSERT INTO cc_courses VALUES (NULL,"RCC","KIN A1","Tennis, Intermediate",1,"E");
INSERT INTO cc_courses VALUES (NULL,"RCC","KIN A1","Tennis, Advanced",1,"E");
INSERT INTO cc_courses VALUES (NULL,"RCC","KIN A2","Golf, Beginning",1,"E");
INSERT INTO cc_courses VALUES (NULL,"RCC","KIN A2","Golf, Intermediate",1,"E");
INSERT INTO cc_courses VALUES (NULL,"RCC","KIN A2","Swimming, Beginning",1,"E");
INSERT INTO cc_courses VALUES (NULL,"RCC","KIN A2","Swimming, Intermediate",1,"E");
INSERT INTO cc_courses VALUES (NULL,"RCC","KIN A3","Swimming, Advanced Skills and Conditioning",1,"E");
INSERT INTO cc_courses VALUES (NULL,"RCC","KIN A3","Beginning Water Aerobics and Deep Water Exercise",1,"E");
INSERT INTO cc_courses VALUES (NULL,"RCC","KIN A3","Intermediate Water Aerobics and Deep Water Exercise",1,"E");
INSERT INTO cc_courses VALUES (NULL,"RCC","KIN A3","Advanced Water Aerobics and Deep Water Exercise",1,"E");
INSERT INTO cc_courses VALUES (NULL,"RCC","KIN V3","Track and Field Techniques: Running Event Techniques",1,"E");
INSERT INTO cc_courses VALUES (NULL,"RCC","KIN V3","Track and Field Techniques, Field Event Techniques",1,"E");
INSERT INTO cc_courses VALUES (NULL,"RCC","KIN 35","Foundation for Fitness and Wellness",3,"E");
INSERT INTO cc_courses VALUES (NULL,"RCC","KIN 36","Wellness: Lifestyle Choices",3,"E");
INSERT INTO cc_courses VALUES (NULL,"RCC","KIN A4","Karate, Beginning",1,"E");
INSERT INTO cc_courses VALUES (NULL,"RCC","KIN A4","Karate, Intermediate",1,"E");
INSERT INTO cc_courses VALUES (NULL,"RCC","KIN A4","T' ai-chi Ch' uan, Beginning",1,"E");
INSERT INTO cc_courses VALUES (NULL,"RCC","KIN A4","T' ai-chi Ch' uan, Intermediate",1,"E");
INSERT INTO cc_courses VALUES (NULL,"RCC","KIN A4","Hatha Yoga, Beginning",1,"E");
INSERT INTO cc_courses VALUES (NULL,"RCC","KIN A4","Hatha Yoga, Intermediate",1,"E");
INSERT INTO cc_courses VALUES (NULL,"RCC","KIN V5","Baseball Fundamentals, Defensive",1,"E");
INSERT INTO cc_courses VALUES (NULL,"RCC","KIN V5","Baseball Fundamentals, Offensive",1,"E");
INSERT INTO cc_courses VALUES (NULL,"RCC","KIN V5","Fastpitch Fundamentals, Offensive",1,"E");
INSERT INTO cc_courses VALUES (NULL,"RCC","KIN V5","Fastpitch Fundamentals, Defensive",1,"E");
INSERT INTO cc_courses VALUES (NULL,"RCC","KIN A5","Fastpitch Softball Fundamentals",1,"E");
INSERT INTO cc_courses VALUES (NULL,"RCC","KIN A5","Slow Pitch Softball",1,"E");
INSERT INTO cc_courses VALUES (NULL,"RCC","KIN A5","Basketball",1,"E");
INSERT INTO cc_courses VALUES (NULL,"RCC","KIN V6","Football Fundamentals, Defensive",1,"E");
INSERT INTO cc_courses VALUES (NULL,"RCC","KIN V6","Football Fundamentals, Offensive",1,"E");
INSERT INTO cc_courses VALUES (NULL,"RCC","KIN A6","Flag Football",1,"E");
INSERT INTO cc_courses VALUES (NULL,"RCC","KIN A6","Soccer",1,"E");
INSERT INTO cc_courses VALUES (NULL,"RCC","KIN A6","Volleyball, Beginning",1,"E");
INSERT INTO cc_courses VALUES (NULL,"RCC","KIN A6","Volleyball, Intermediate",1,"E");
INSERT INTO cc_courses VALUES (NULL,"RCC","KIN A6","Volleyball, Advanced",1,"E");
INSERT INTO cc_courses VALUES (NULL,"RCC","KIN V7","Water Polo Techniques",2,"E");
INSERT INTO cc_courses VALUES (NULL,"RCC","KIN A7","Sand Volleyball: Intermediate/Advanced",1,"E");
INSERT INTO cc_courses VALUES (NULL,"RCC","KIN A7","Hiking and Backpacking Activities",1,"E");
INSERT INTO cc_courses VALUES (NULL,"RCC","KIN A7","Walking for Fitness",1,"E");
INSERT INTO cc_courses VALUES (NULL,"RCC","KIN A7","Walking for Fitness: Beginning",1,"E");
INSERT INTO cc_courses VALUES (NULL,"RCC","KIN A7","Walking for Fitness: Intermediate",1,"E");
INSERT INTO cc_courses VALUES (NULL,"RCC","KIN A7","Jogging for Fitness",1,"E");
INSERT INTO cc_courses VALUES (NULL,"RCC","KIN A7","Jogging for Fitness, Beginning",1,"E");
INSERT INTO cc_courses VALUES (NULL,"RCC","KIN A7","Jogging for Fitness, Intermediate",1,"E");
INSERT INTO cc_courses VALUES (NULL,"RCC","KIN A7","Jogging for Fitness, Advanced",1,"E");
INSERT INTO cc_courses VALUES (NULL,"RCC","KIN V7","Long Distance Running",1,"E");
INSERT INTO cc_courses VALUES (NULL,"RCC","KIN A8","Triathlon Techniques",1,"E");
INSERT INTO cc_courses VALUES (NULL,"RCC","KIN A8","Physical Fitness",1,"E");
INSERT INTO cc_courses VALUES (NULL,"RCC","KIN A8","Physical Fitness, Beginning",1,"E");
INSERT INTO cc_courses VALUES (NULL,"RCC","KIN A8","Physical Fitness, Intermediate",1,"E");
INSERT INTO cc_courses VALUES (NULL,"RCC","KIN A8","Speed, Agility, and Quickness Training",1,"E");
INSERT INTO cc_courses VALUES (NULL,"RCC","KIN A8","Kickboxing Aerobics",1,"E");
INSERT INTO cc_courses VALUES (NULL,"RCC","KIN A8","Step Aerobics",1,"E");
INSERT INTO cc_courses VALUES (NULL,"RCC","KIN A8","Step Aerobics, Intermediate",1,"E");
INSERT INTO cc_courses VALUES (NULL,"RCC","KIN A8","Step Aerobics, Advanced",1,"E");
INSERT INTO cc_courses VALUES (NULL,"RCC","KIN A8","Beginning Body Sculpting",1,"E");
INSERT INTO cc_courses VALUES (NULL,"RCC","KIN A8","Intermediate Body Sculpting",1,"E");
INSERT INTO cc_courses VALUES (NULL,"RCC","KIN A8","Advanced Body Sculpting",1,"E");
INSERT INTO cc_courses VALUES (NULL,"RCC","KIN A9","Weight Training",1,"E");
INSERT INTO cc_courses VALUES (NULL,"RCC","KIN A9","Weight Training, Advanced",1,"E");
INSERT INTO cc_courses VALUES (NULL,"RCC","KIN V9","Weight Training Varsity Athletes",1,"E");
INSERT INTO cc_courses VALUES (NULL,"RCC","KIN V9","In Season Varsity Sport Conditioning",1,"E");
INSERT INTO cc_courses VALUES (NULL,"RCC","KIN V9","Out of Season Varsity Sport Conditioning",1,"E");
INSERT INTO cc_courses VALUES (NULL,"RCC","KOR 1","Korean 1",5,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","KOR 2","Korean 2",5,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","KOR 11","Culture and Civilization",3,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","LAT 1","Latin 1",5,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","LAT 2","Latin 2",5,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","MAT 1A","Calculus I",4,"B4");
INSERT INTO cc_courses VALUES (NULL,"RCC","MAT 1B","Calculus II",4,"B4");
INSERT INTO cc_courses VALUES (NULL,"RCC","MAT 1C","Calculus III",4,"B4");
INSERT INTO cc_courses VALUES (NULL,"RCC","MAT 2","Differential Equations",4,"B4");
INSERT INTO cc_courses VALUES (NULL,"RCC","MAT 2A","Solid Analytic Geometry and Calculus / Differential Equations I",4,"B4");
INSERT INTO cc_courses VALUES (NULL,"RCC","MAT 2B","Solid Analytic Geometry and Calculus / Differential Equations II",4,"B4");
INSERT INTO cc_courses VALUES (NULL,"RCC","MAT 3","Linear Algebra",3,"B4");
INSERT INTO cc_courses VALUES (NULL,"RCC","MAT 4","Finite Mathematics",3,"B4");
INSERT INTO cc_courses VALUES (NULL,"RCC","MAT 5","Calculus for Business and Life Science",4,"B4");
INSERT INTO cc_courses VALUES (NULL,"RCC","MAT 6","Discrete Mathematics for Computer Science",3,"B4");
INSERT INTO cc_courses VALUES (NULL,"RCC","MAT 9","Introduction to Scientific Computer Programming",3,"B4");
INSERT INTO cc_courses VALUES (NULL,"RCC","MAT 10","Precalculus",4,"B4");
INSERT INTO cc_courses VALUES (NULL,"RCC","MAT 11","College Algebra",4,"B4");
INSERT INTO cc_courses VALUES (NULL,"RCC","MAT 12","Statistics",4,"B4");
INSERT INTO cc_courses VALUES (NULL,"RCC","MAT 12","Honors Statistics",4,"B4");
INSERT INTO cc_courses VALUES (NULL,"RCC","MAT 25","Mathematics for the Liberal Arts Student",3,"B4");
INSERT INTO cc_courses VALUES (NULL,"RCC","MAT 26","Math for Elementary School Teachers",3,"B4");
INSERT INTO cc_courses VALUES (NULL,"RCC","MAT 32","Introduction to Symbolic Logic Logic",3,"A3");
INSERT INTO cc_courses VALUES (NULL,"RCC","MAT 36","Trigonometry",4,"B4");
INSERT INTO cc_courses VALUES (NULL,"RCC","MIC 1","Microbiology",4,"B2");
INSERT INTO cc_courses VALUES (NULL,"RCC","MIC 1","Microbiology",4,"B3");
INSERT INTO cc_courses VALUES (NULL,"RCC","MIL 1","Military History of the United States to 1900 United States to 1900",3,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","MIL 2","Military History of the United States since 1900 United States since 1900",3,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","MUS 3","Fundamentals of Music",4,"C1");
INSERT INTO cc_courses VALUES (NULL,"RCC","MUS 4","Harmony I",4,"C1");
INSERT INTO cc_courses VALUES (NULL,"RCC","MUS 5","Harmony II",4,"C1");
INSERT INTO cc_courses VALUES (NULL,"RCC","MUS 6","Music Theory III",4,"C1");
INSERT INTO cc_courses VALUES (NULL,"RCC","MUS 7","Counterpoint",3,"C1");
INSERT INTO cc_courses VALUES (NULL,"RCC","MUS 19","Music Appreciation",3,"C1");
INSERT INTO cc_courses VALUES (NULL,"RCC","MUS 19","Honors Music Appreciation",3,"C1");
INSERT INTO cc_courses VALUES (NULL,"RCC","MUS 20","Great Composers and Music Masterpieces Before 1820",3,"C1");
INSERT INTO cc_courses VALUES (NULL,"RCC","MUS 21","Great Composers and Music Masterpieces After 1820",3,"C1");
INSERT INTO cc_courses VALUES (NULL,"RCC","MUS 22","Survey of Music Literature",3,"C1");
INSERT INTO cc_courses VALUES (NULL,"RCC","MUS 23","History of Rock and Roll",3,"C1");
INSERT INTO cc_courses VALUES (NULL,"RCC","MUS 25","Jazz Appreciation",3,"C1");
INSERT INTO cc_courses VALUES (NULL,"RCC","MUS 26","Film Music Appreciation",3,"C1");
INSERT INTO cc_courses VALUES (NULL,"RCC","MUS 89","Music of Multicultural America",3,"C1");
INSERT INTO cc_courses VALUES (NULL,"RCC","MUS 89","Honors Music of Multicultural America",3,"C1");
INSERT INTO cc_courses VALUES (NULL,"RCC","OCE 1","Introduction to Oceanography",3,"B1");
INSERT INTO cc_courses VALUES (NULL,"RCC","OCE 1L","Introduction to Oceanography Laboratory",1,"B1");
INSERT INTO cc_courses VALUES (NULL,"RCC","PHI 10","Introduction to Philosophy",3,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","PHI 10","Honors Introduction to Philosophy",3,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","PHI 11","Critical Thinking",3,"A3");
INSERT INTO cc_courses VALUES (NULL,"RCC","PHI 12","Introduction to Ethics: Contemporary Moral Issues",3,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","PHI 13","Philosophy of Art",3,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","PHI 14","Survey of Black Thought",3,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","PHI 15","Bio-Medical Ethics",3,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","PHI 16","Moral Reasoning in Business",3,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","PHI 19","Native American Thought",3,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","PHI 20","History of Western Philosophy I: Greek, Roman and Medieval",3,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","PHI 21","History of Western Philosophy II: Modern and Contemporary",3,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","PHI 22","Philosophy of Science",3,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","PHI 30","Critical and Speculative Philosophy",3,"A3");
INSERT INTO cc_courses VALUES (NULL,"RCC","PHI 31","Value Disciplines",3,"A3");
INSERT INTO cc_courses VALUES (NULL,"RCC","PHI 32","Introduction to Symbolic Logic Logic",3,"A3");
INSERT INTO cc_courses VALUES (NULL,"RCC","PHI 33","Introduction to Social and Political Philosophy",3,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","PHI 35","Philosophy of Religion",3,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","PHP 4","Nutrition",3,"E");
INSERT INTO cc_courses VALUES (NULL,"RCC","PHP 26","Introduction to Dance",3,"C1");
INSERT INTO cc_courses VALUES (NULL,"RCC","PHP 35","Foundation for Fitness and Wellness",3,"E");
INSERT INTO cc_courses VALUES (NULL,"RCC","PHP 36","Wellness: Lifestyle Choices",3,"E");
INSERT INTO cc_courses VALUES (NULL,"RCC","PHP 44","Health Needs in A Modern Society",3,"E");
INSERT INTO cc_courses VALUES (NULL,"RCC","PHS 1","Introduction to Physical Science",3,"B1");
INSERT INTO cc_courses VALUES (NULL,"RCC","PHS 5","Weather and Climate",3,"B1");
INSERT INTO cc_courses VALUES (NULL,"RCC","PHS 17","Introduction to the Development of Modern Science",3,"D6");
INSERT INTO cc_courses VALUES (NULL,"RCC","PHY 2A","General Physics I",4,"B1");
INSERT INTO cc_courses VALUES (NULL,"RCC","PHY 2A","General Physics I",4,"B3");
INSERT INTO cc_courses VALUES (NULL,"RCC","PHY 2B","General Physics II",4,"B1");
INSERT INTO cc_courses VALUES (NULL,"RCC","PHY 2B","General Physics II",4,"B3");
INSERT INTO cc_courses VALUES (NULL,"RCC","PHY 4A","Mechanics",4,"B1");
INSERT INTO cc_courses VALUES (NULL,"RCC","PHY 4A","Mechanics",4,"B3");
INSERT INTO cc_courses VALUES (NULL,"RCC","PHY 4B","Electricity and Magnetism",4,"B1");
INSERT INTO cc_courses VALUES (NULL,"RCC","PHY 4B","Electricity and Magnetism",4,"B3");
INSERT INTO cc_courses VALUES (NULL,"RCC","PHY 4C","Heat, Light and Waves",4,"B1");
INSERT INTO cc_courses VALUES (NULL,"RCC","PHY 4C","Heat, Light and Waves",4,"B3");
INSERT INTO cc_courses VALUES (NULL,"RCC","PHY 4D","Modern Physics",4,"B1");
INSERT INTO cc_courses VALUES (NULL,"RCC","PHY 4D","Modern Physics",4,"B3");
INSERT INTO cc_courses VALUES (NULL,"RCC","PHY 10","Introduction to General Physics",3,"B1");
INSERT INTO cc_courses VALUES (NULL,"RCC","PHY 11","Physics Lab",1,"B1");
INSERT INTO cc_courses VALUES (NULL,"RCC","PHY 11","Physics Lab",1,"B3");
INSERT INTO cc_courses VALUES (NULL,"RCC","POL 1","American Politics",3,"D2");
INSERT INTO cc_courses VALUES (NULL,"RCC","POL 1","American Politics",3,"D8");
INSERT INTO cc_courses VALUES (NULL,"RCC","POL 1H","Honors American Politics",3,"D8");
INSERT INTO cc_courses VALUES (NULL,"RCC","POL 2","Comparative Politics",3,"D2");
INSERT INTO cc_courses VALUES (NULL,"RCC","POL 2","Comparative Politics",3,"D8");
INSERT INTO cc_courses VALUES (NULL,"RCC","POL 2H","Honors Comparative Politics",3,"D8");
INSERT INTO cc_courses VALUES (NULL,"RCC","POL 3","Introduction to Politics",3,"D2");
INSERT INTO cc_courses VALUES (NULL,"RCC","POL 3","Introduction to Politics",3,"D8");
INSERT INTO cc_courses VALUES (NULL,"RCC","POL 4","Introduction to World Politics",3,"D2");
INSERT INTO cc_courses VALUES (NULL,"RCC","POL 4H","Honors Introduction to World Politics",3,"D8");
INSERT INTO cc_courses VALUES (NULL,"RCC","POL 5","The Law and Politics",3,"D2");
INSERT INTO cc_courses VALUES (NULL,"RCC","POL 5","The Law and Politics",3,"D8");
INSERT INTO cc_courses VALUES (NULL,"RCC","POL 6","Introduction to Political Economy Economy",3,"D2");
INSERT INTO cc_courses VALUES (NULL,"RCC","POL 7A","Current Political Issues",3,"D2");
INSERT INTO cc_courses VALUES (NULL,"RCC","POL 7A","Current Political Issues",3,"D8");
INSERT INTO cc_courses VALUES (NULL,"RCC","POL 7B","Current Political Issues",3,"D2");
INSERT INTO cc_courses VALUES (NULL,"RCC","POL 7B","Current Political Issues",3,"D8");
INSERT INTO cc_courses VALUES (NULL,"RCC","POL 7C","Current Political Issues",3,"D2");
INSERT INTO cc_courses VALUES (NULL,"RCC","POL 7C","Current Political Issues",3,"D8");
INSERT INTO cc_courses VALUES (NULL,"RCC","POL 7D","Current Political Issues",3,"D2");
INSERT INTO cc_courses VALUES (NULL,"RCC","POL 7D","Current Political Issues",3,"D8");
INSERT INTO cc_courses VALUES (NULL,"RCC","POL 8","Introduction to Public Administration and Policy Development",3,"D2");
INSERT INTO cc_courses VALUES (NULL,"RCC","POL 9","Law in American Society",3,"D2");
INSERT INTO cc_courses VALUES (NULL,"RCC","POL 9","Law in American Society",3,"D8");
INSERT INTO cc_courses VALUES (NULL,"RCC","POL 10","International Organizations",3,"D2");
INSERT INTO cc_courses VALUES (NULL,"RCC","POL 10","International Organizations",3,"D8");
INSERT INTO cc_courses VALUES (NULL,"RCC","POL 11","Political Theory",3,"D8");
INSERT INTO cc_courses VALUES (NULL,"RCC","POL 12","State and Local Politics",3,"D8");
INSERT INTO cc_courses VALUES (NULL,"RCC","POL 13","Introduction to American Foreign Policy",3,"D8");
INSERT INTO cc_courses VALUES (NULL,"RCC","POR 1","Portuguese 1",5,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","POR 2","Portuguese 2",5,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","PSY 1","General Psychology",3,"D4");
INSERT INTO cc_courses VALUES (NULL,"RCC","PSY 1","General Psychology",3,"D9");
INSERT INTO cc_courses VALUES (NULL,"RCC","PSY 1H","Honors General Psychology",3,"D9");
INSERT INTO cc_courses VALUES (NULL,"RCC","PSY 2","Biological Psychology",3,"B2");
INSERT INTO cc_courses VALUES (NULL,"RCC","PSY 4","Intro to Experimental Design",3,"D9");
INSERT INTO cc_courses VALUES (NULL,"RCC","PSY 8","Introduction to Social Psychology",3,"D9");
INSERT INTO cc_courses VALUES (NULL,"RCC","PSY 9","Developmental Psychology",3,"D4");
INSERT INTO cc_courses VALUES (NULL,"RCC","PSY 9","Developmental Psychology",3,"D9");
INSERT INTO cc_courses VALUES (NULL,"RCC","PSY 9","Developmental Psychology",3,"E");
INSERT INTO cc_courses VALUES (NULL,"RCC","PSY 33","Theories of Personality",3,"D9");
INSERT INTO cc_courses VALUES (NULL,"RCC","PSY 33","Theories of Personality",3,"E");
INSERT INTO cc_courses VALUES (NULL,"RCC","PSY 35","Abnormal Psychology",3,"D9");
INSERT INTO cc_courses VALUES (NULL,"RCC","PSY 50","Research Methods in Psychology",4,"D9");
INSERT INTO cc_courses VALUES (NULL,"RCC","REA 4","Critical Reading as Critical Thinking",3,"A3");
INSERT INTO cc_courses VALUES (NULL,"RCC","RUS 1","Russian 1",5,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","RUS 1A","Russian 1A",2.5,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","RUS 1B","Russian 1B",2.5,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","RUS 2","Russian 2",5,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","RUS 3","Russian 3",5,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","RUS 11","Culture and Civilization",3,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","SOC 1","Introduction to Sociology",3,"D0");
INSERT INTO cc_courses VALUES (NULL,"RCC","SOC 1","Introduction to Sociology",3,"D1");
INSERT INTO cc_courses VALUES (NULL,"RCC","SOC 1H","Honors Introduction to Sociology",3,"D0");
INSERT INTO cc_courses VALUES (NULL,"RCC","SOC 2","American Social Problems",3,"D0");
INSERT INTO cc_courses VALUES (NULL,"RCC","SOC 2","American Social Problems",3,"D1");
INSERT INTO cc_courses VALUES (NULL,"RCC","SOC 3","Social Inequality",3,"D0");
INSERT INTO cc_courses VALUES (NULL,"RCC","SOC 10","Race and Ethnic Relations",3,"D1");
INSERT INTO cc_courses VALUES (NULL,"RCC","SOC 10","Race and Ethnic Relations",3,"D3");
INSERT INTO cc_courses VALUES (NULL,"RCC","SOC 11","Introduction to the Sociology of Health and Medicine",3,"D0");
INSERT INTO cc_courses VALUES (NULL,"RCC","SOC 12","Marriage and Family Relations Relations",3,"D0");
INSERT INTO cc_courses VALUES (NULL,"RCC","SOC 15","Women in American Society",3,"D0");
INSERT INTO cc_courses VALUES (NULL,"RCC","SOC 15","Women in American Society",3,"D1");
INSERT INTO cc_courses VALUES (NULL,"RCC","SOC 15","Women in American Society",3,"D4");
INSERT INTO cc_courses VALUES (NULL,"RCC","SOC 17","Introduction to Social Gerontology",3,"D0");
INSERT INTO cc_courses VALUES (NULL,"RCC","SOC 20","Introduction to Criminology",3,"D0");
INSERT INTO cc_courses VALUES (NULL,"RCC","SOC 20","Introduction to Criminology",3,"D1");
INSERT INTO cc_courses VALUES (NULL,"RCC","SOC 25","Introduction to the Sociology of Sex and Gender",3,"D0");
INSERT INTO cc_courses VALUES (NULL,"RCC","SOC 30","Introduction to Formal Organizations",3,"D0");
INSERT INTO cc_courses VALUES (NULL,"RCC","SOC 35","Sociology of the Black Community",3,"D1");
INSERT INTO cc_courses VALUES (NULL,"RCC","SOC 42","Introduction to Urban Sociology",3,"D0");
INSERT INTO cc_courses VALUES (NULL,"RCC","SOC 45","Childhood and Culture",3,"D0");
INSERT INTO cc_courses VALUES (NULL,"RCC","SOC 45","Childhood and Culture",3,"D1");
INSERT INTO cc_courses VALUES (NULL,"RCC","SOC 49","Introduction to Research Methodology",5,"D0");
INSERT INTO cc_courses VALUES (NULL,"RCC","SOC 50","Introduction to Social Research Methods",3,"D0");
INSERT INTO cc_courses VALUES (NULL,"RCC","SPA 1","Spanish 1",5,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","SPA 1A","Spanish 1A",2.5,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","SPA 1B","Spanish 1B",2.5,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","SPA 1H","Honors Spanish 1H",5,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","SPA 2","Spanish 2",5,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","SPA 2A","Spanish 2A",2.5,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","SPA 2B","Spanish 2B",2.5,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","SPA 2H","Honors Spanish 2",5,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","SPA 3","Spanish 3",5,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","SPA 3N","Spanish for Spanish Speakers",5,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","SPA 4","Spanish 4",5,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","SPA 8","Intermediate Conversation",3,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","SPA 8A","Intermediate Conversation I",3,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","SPA 8B","Intermediate Conversation II",3,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","SPA 11","Spanish Culture and Civilization",3,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","SPA 12","Latin American Culture and Civilization",3,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","COM 3A","Argumentation and Debate",3,"A3");
INSERT INTO cc_courses VALUES (NULL,"RCC","SP COM","Public Speaking",3,"A1");
INSERT INTO cc_courses VALUES (NULL,"RCC","SP COM","Persuasion in Rhetorical Perspective",3,"A3");
INSERT INTO cc_courses VALUES (NULL,"RCC","SP COM","Argumentation and Debate",3,"A3");
INSERT INTO cc_courses VALUES (NULL,"RCC","SP COM","The Psychology of Argumentation",3,"A3");
INSERT INTO cc_courses VALUES (NULL,"RCC","SP COM","The Deliberative Process",3,"A3");
INSERT INTO cc_courses VALUES (NULL,"RCC","SP COM","Small Group Problem Solving",3,"A3");
INSERT INTO cc_courses VALUES (NULL,"RCC","SP COM","Interpersonal Communication",3,"A1");
INSERT INTO cc_courses VALUES (NULL,"RCC","SP COM","Gender and Communication",3,"D4");
INSERT INTO cc_courses VALUES (NULL,"RCC","SPE 1","Public Speaking",3,"A1");
INSERT INTO cc_courses VALUES (NULL,"RCC","SPE 1H","Honors Public Speaking",3,"A1");
INSERT INTO cc_courses VALUES (NULL,"RCC","SPE 2","Persuasion in Rhetorical Perspective",3,"A3");
INSERT INTO cc_courses VALUES (NULL,"RCC","SPE 3A","Argumentation and Debate",3,"A3");
INSERT INTO cc_courses VALUES (NULL,"RCC","SPE 4A","The Psychology of Argumentation",3,"A3");
INSERT INTO cc_courses VALUES (NULL,"RCC","SPE 5","Parliamentary Procedure",1,"A3");
INSERT INTO cc_courses VALUES (NULL,"RCC","SPE 6","Dynamics of Small Group Communication",3,"A1");
INSERT INTO cc_courses VALUES (NULL,"RCC","SPE 9","Interpersonal Communication",3,"A1");
INSERT INTO cc_courses VALUES (NULL,"RCC","SPE 9","Interpersonal Communication",3,"D7");
INSERT INTO cc_courses VALUES (NULL,"RCC","SPE 9H","Honors Interpersonal Communication",3,"A1");
INSERT INTO cc_courses VALUES (NULL,"RCC","SPE 11","Storytelling",3,"C1");
INSERT INTO cc_courses VALUES (NULL,"RCC","SPE 12","Intercultural Communication",3,"D7");
INSERT INTO cc_courses VALUES (NULL,"RCC","SPE 13","Gender Communication",3,"D4");
INSERT INTO cc_courses VALUES (NULL,"RCC","TEL 12","History of American Film",3,"C2");
INSERT INTO cc_courses VALUES (NULL,"RCC","TEL 41","Introduction to Telecommunication",3,"D7");
INSERT INTO cc_courses VALUES (NULL,"RCC","TEL 65","The Director's Art in Filmmaking",3,"C1");
INSERT INTO cc_courses VALUES (NULL,"RCC","THE 3","Introduction to the Theater",3,"C1");
INSERT INTO cc_courses VALUES (NULL,"RCC","THE 9","Dramatic Literature-Script Analysis",3,"C1");
INSERT INTO cc_courses VALUES (NULL,"RCC","THE 29","Musical Theater Appreciation",3,"C1");

